---
# tasks file for ansible_openjdk8__

- name: install requirements
  package: name={{ item }} state=installed
  with_items: expect

- name: install openjdk8
  package:
    name: java-1.8.0-openjdk
    state: installed

- name: copy config script
  copy: dest={{config_script_path}} owner=root group=root mode=755 src=defaultjdk8.sh

- name: config default java to jdk8
  shell: '{{config_script_path}}'
